name: CI
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  lint:
    name: Lint
    strategy:
      matrix:
        go: ["1.19", "1.20", "1.21", "1.22", "1.23", "1.24"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          version: v2.3.0

  test:
    name: Test
    strategy:
      matrix:
        go: ["1.19", "1.20", "1.21", "1.22", "1.23", "1.24"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Test
        run: |
          go vet .
          go build .
          go test -count=1 -covermode=count -coverprofile=coverage.out .

  legacy-test:
    name: Legacy Tests
    strategy:
      matrix:
        go: ["1.19", "1.20", "1.21", "1.22", "1.23"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Test
        run: |
          go vet -tags=legacy .
          go build -tags=legacy .
          GODEBUG=x509sha1=1 go test -tags=legacy -count=1 -covermode=count -coverprofile=coverage.out . -run "^TestLegacy.*$"
