name: CI
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env: 
  GODEBUG: x509sha1=1

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.23'  # Use a stable version for linting
    - name: Install golangci-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    - name: Run golangci-lint
      run: golangci-lint run

  test:
    name: Test
    strategy:
      matrix:
        go: ['1.19', '1.20', '1.21', '1.22', '1.23', '1.24']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
    - name: Test
      env:
        # set this environment variable to true so tests can be run with the
        # sha1 algorithm. Without this set, tests fail because Go notes the
        # SHA1 algorithm as insecure
        GODEBUG: x509sha1=1
      run: |
        go vet .
        go build .
        if [[ "${{ matrix.go }}" == "1.24" ]]; then
          # For Go 1.24, skip tests that fail due to SHA1 restrictions
          go test -count=1 -covermode=count -coverprofile=coverage.out -skip "TestVerifyEC2|TestDSASignWithOpenSSLAndVerify|TestSign$|TestSignWithoutAttributes|TestSignWithOpenSSLAndVerify" .
        else
          go test -count=1 -covermode=count -coverprofile=coverage.out .
        fi
