name: CI
on: [push, pull_request]

env: 
  GODEBUG: x509sha1=1

jobs:
  test:
    name: Test
    strategy:
      matrix:
        go: ['1.19', '1.20', '1.21', '1.22', '1.23']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
    - name: Test
      env:
        # set this environment variable to true so tests can be run with the
        # sha1 algorithm. Without this set, tests fail because Go notes the
        # SHA1 algorithm as insecure
        GODEBUG: x509sha1=1
      run: go vet . && go build . && go test -count=1 -covermode=count -coverprofile=coverage.out .
